<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</head>
<body>
	<table class="w-100" cellpadding="4">
			<tr height="40">
			<td  colspan=3><?php $this->getChild('message'); ?></td>
		</tr>
		<tr height="250">
			<td><?php echo $this->getChildHtml('left'); ?></td>
			<td><?php echo $this->getChildHtml('content'); ?></td>
			<td><?php echo $this->getChildHtml('right'); ?></td>
		</tr>
		<tr height="50">
			<td colspan=3><?php echo $this->getChildHtml('footer'); ?></td>
		</tr>
	</table>
</body>
</html>